### ISSUE TITLE
Integrate libVitaMTP to eliminate the need of QCMA

### ISSUE THREAD

**Issue by noahc3** [noahc3/auto-h-encore#1]
I don't know C, so if anyone would be willing to help integrate libVitaMTP to make this application an all-in-one solution, please do!

**Comment by noahc3** [comment]
To get this done, we either need a command line CMA tool like yifanlu's OpenCMA (OpenCMA needs an updated libvitaMTP to work with newer vita firmwares), or a C# wrapper for the libVitaMTP dll. I'm not sure how to go about writing the wrapper, and I can't update OpenCMA because I don't know C. Any help with this would be appreciated!

**Comment by yoshi314** [comment]
isn't that just the case of building opencma against newer libvitamtp ?

**Comment by noahc3** [comment]
Maybe, but I haven't had luck getting libvitamtp to compile for Windows at all.

**Comment by ShroomKing** [comment]
I have libvitamtp working on windows, and made a program that should transfer h-encore automatically when running the exe.  But i can't connect the vita to it cuz it tells me to "Update Content Manager Assistant on your PC"

CORRECTION: by "should transfer h-encore automatically" i actually meant it should detect the h-encore app automatically when it's in the same folder as the exe, you still need to use cma on your vita to transfer the app to it.

So it seems like, unless someone updates the protocols libvitamtp is using, we won't be able to do this.
Also i'm not familiar with the qcma source code, but we might(or might not, i dunno yet) be able to use their protocols for libvitamtp, but i'm gonna have to research that when i have time. 

As for compiling on windows, the makefiles that get created with mingw64/32 are a damn mess. they don't actually link winsock2, hence linking errors.

**Comment by noahc3** [comment]
You need to use [codestations libvitamtp fork](https://github.com/codestation/vitamtp) which works with latest firmwares. It does not include openCMA, however, so I need some other method to integrate it. Also I had to manually pass in the mingw32 compiler into configure to make it find the winsock2 library correctly.

Apparently codestation [had compilation scripts for Windows using MSVC, but lost them](https://github.com/codestation/vitamtp/issues/8).

EDIT: Note  that I still can't build this version, something about missing linker files. I sort of understand the problem but am unsure how to fix it and Google isn't very helpful.

**Comment by noahc3** [comment]
I've decided to just integrate QCMA itself into the app like the other tools. It will be a lot easier than getting  libvitamtp working, and will still be just as silent/automated.

**Comment by noahc3** [comment]
QCMA full integration and automation complete in commit 1c1a81aeafdc34b580c074cc974756c2181ad2c3.
