### ISSUE TITLE
Support for multiple PSN accounts

### ISSUE THREAD

**Issue by ghost** [noahc3/auto-h-encore#12]
https://github.com/noahc3/auto-h-encore/commit/336ce989490825a097cc049fea762a608d0ac3bc adds support for automatic AID import but it needs to be a list rather than a set value, as multiple PSN accounts make up multiple folders.

**Comment by ghost** [comment]
To add to my initial idea, the list needs to be a dynamic one, created from folder names under "PS Vita/APP" and select the first one on the list as default (so normal people don't mess with it)

**Comment by noahc3** [comment]
I think it's easier for the user to just plug in the Vita they want. When you plug in a Vita, QCMA updates the registry with the information for the active PSN account on that Vita. If a user is inclined enough to know that they want it switched, they should be able to get it themselves.
