### ISSUE TITLE
Translations need to be updated for v0.4.0

### ISSUE THREAD

**Issue by noahc3** [noahc3/auto-h-encore#27]
@yexun1995 @RY0M43CH1Z3N @M2l2koPOWER @theheroGAC @barbabarros @wababc 

Version 0.4.0 (now committed to master) has new and updated strings.

Specifically, the following values are either new or were changed:
lbl_ConnectionMethod, lbl_UnplugVita, lbl_InstallingUSB, lbl_WifiProblems, txtblock_BeforeRunning, txtblock_USBInstructions, txtblock_WifiInstructions, btn_Next, btn_USB, btn_Wifi, log_SearchingForQCMA, log_FoundQCMA, log_KillingQCMA, log_QCMARegistry, log_ScrubAID, log_Prompt, and step 1 of info_Finish

The English versions were already copied to each dictionary, just replace the values.

If you guys aren't busy and willing to help out, it would be great if you could update your respective languages! Thanks!

**Edit: All languages complete except Spanish and a tiny bit of French.**

**Comment by yexun1995** [comment]
The   txtblock_WifiInstructions .
5  6  7 
Is the order right?
I think 675 is better.

**Comment by yexun1995** [comment]
n5. Select Register\r\n6.Select the name of your PC\r\n7. Enter the code that appears on your PC
(Wifi connect)
The right order is 675.Just change language to English and tested.

**Comment by wababc** [comment]
French translated and tested

**Comment by M2l2koPOWER** [comment]
dont understand what a mess about "txtblock_WifiInstructions".
maybe due to the fact that in my russian lang i understand the instructions
little differently,but i see no reason to change the order

2018-07-08 15:29 GMT+03:00 wababc <notifications@github.com>:

**Comment by noahc3** [comment]
@yexun1995 It's definitely Register Device > [PC Name] > Code for me. Am I misunderstanding something?

**Comment by noahc3** [comment]
@barooney Forgot to tag you, could you help update German too?

**Comment by yexun1995** [comment]
According to the video.
https://m.youtube.com/watch?v=pEgCTxofu1A
http://wololo.net/2015/05/16/how-to-connect-your-lower-vita-firmware-to-your-pc-via-wifi/
 And.My question.When I start my translation,it is just like this.
5. Select Register\    6.Select the name of your PC  \7. Enter the code that appears on your PC
Q:what is the select register?the register button?I can find it only if I choosed the pc name and typed in the code qcma show me.just like the video.So.Do you know what I mean?

**Comment by M2l2koPOWER** [comment]
oh,i think step 5 just unnecessary, and we all should fix it on our
translates (and english original too)

2018-07-08 19:06 GMT+03:00 Yexun <notifications@github.com>:

**Comment by noahc3** [comment]
It's only unnecessary if you've registered your PC before. I think most people using this won't have done so.

**Comment by M2l2koPOWER** [comment]
ok,i understand what's the problem. Steps order is wrong, I gonna fix it

2018-07-08 19:15 GMT+03:00 Noah <notifications@github.com>:

**Comment by M2l2koPOWER** [comment]
oh lol only now i saw that left language.cs in "auto h-encore" instead of
"auto h-encore/auto h-encore"

**Comment by yexun1995** [comment]
The first time for a PSV to connect to PC with Wifi:
Content Manager----Copy Content-----PC-----Wifi.
Then there is a page which names Register Devices.
I can choose the name of my PC.
And the button Register Device only appears when I had connected to any PC with wifi before.

But if someone had connected to PC with Wifi,it will be a little different.
Content Manager----Copy Content-----PC-----Wifi.
Then there is a page which names PC.
There is a button :  Register Device
Click on it,and it turn to the page Register Device.

**Comment by noahc3** [comment]
Oh, it jumps to register by default if nothing is registered then. Good to know! I'll make corrections.

**Comment by noahc3** [comment]
The following languages are complete:
English, Simplified Chinese, Russian, Italian, Brazilian Portuguese, and German.

I'm going to release v0.4.0 with these languages, plus French since there is only one line left untranslated. I'll re-add Spanish if that gets updated.

Tagging @Retsukun  to possibly help finish French.

Thanks everyone!

**Comment by barooney** [comment]
@noahc3 Updated the German translation in #42. 👍

**Comment by wababc** [comment]
Which line is left untranslated in french ? maybe the issue tracker but its just because its a link. otherwise could you tell me which one is it ? @noahc3

**Comment by noahc3** [comment]
Retsukun already updated it, it was step 1 of info_Finish. Thank you though!

**Comment by barbabarros** [comment]
"Holds your hand along the way." 
I love it. :D

**Comment by RY0M43CH1Z3N** [comment]
Spanish now updated, thanks for your great work!

**Comment by noahc3** [comment]
All the translations are done. Thanks everyone for the work!
