### ISSUE TITLE
Allow users to use previously downloaded files

### ISSUE THREAD

**Issue by noahc3** [noahc3/auto-h-encore#3]
Users with unstable or slow internet should be able to use files they've already downloaded (especially large ones like the bittersmile pkg). This program could use file hashes to make sure the files provided can be used without needing to redownload.

**Comment by ghost** [comment]
A better alternative would be to:
1) Check if "bittersmile.pkg" is present.
2) If present, compare its MD5 to a hardcoded one so we know it's usable.
3) If it matches, activate a checkbox that says "Use the existing "bittersmile.pkg"" (normally grayed out) that skips the download process.
4) If it doesn't / It's not present, download it and continue.

**Comment by noahc3** [comment]
You can now choose to import your own files as of commit fea97ad.
Application now checks if files were already download correctly and uses them if so (unless user specifies to delete them) as of commit 306d50f.

Imports always take precedence over existing files.
