### ISSUE TITLE
To-go Net Framework (from Azure) download pages can go down often

### ISSUE THREAD

**Issue by ghost** [noahc3/auto-h-encore#4]
As a matter of fact, they are at the time of writing this.  [A much better link to direct the user to would be here.](https://www.microsoft.com/net/download/dotnet-framework-runtime/net452)

**Comment by noahc3** [comment]
Don't believe I've provided a link on here anywhere, but I'll add that link to the README, probably should have done that in the first place.

**Comment by ghost** [comment]
It's in the program. If you didn't do it, it'may be on the compiler side. Try uninstalling 4.5.2, restarting and see. Directs to an Azure site. Maybe it's changeable or needs an upgrade? 

Another way to fix this would be to use a wrapper to detect missing framework before the program itself does and directing the user to the correct link.

**Comment by noahc3** [comment]
On my machine it actually hooks into Windows Update to download .NET, which imo is worse. It seems it is being handled by Windows. I should be able to edit the bootstrapper and change this functionality. I'll see what I can do.

**Comment by noahc3** [comment]
The bootstrap cannot be changed to address issue. I don't think this is enough of a problem to go through the trouble of creating and maintaining an additional wrapper just to check for .NET, especially since .NET is bundled with Windows 10 anyways. Wont fix.
