### ISSUE TITLE
I can not open the vita shell

### ISSUE THREAD

**Issue by KuramaWhite** [noahc3/auto-h-encore#51]
Hi, can you help me? when i install vitashell and open, it gives an error, i can not start vitashell, the error of as: (c2-12828-1) saved core file succeeded.ux0: data / psp2core-1530659196-0x0000212f71-eboot.bin.psp2dmp , I have already restarted, have already formatted my ps vita and nadaaa how to solve this ???

**Comment by noahc3** [comment]
Try the following:
 * Remove any game cards
 * Turn off bluetooth
 * Uninstall VitaShell (hold the bubble, click [...], uninstall)
 * Reinstall VitaShell in h-encore
 * Launch Again

**Comment by barbabarros** [comment]
also make sure you are using the latest vitashell release.

**Comment by KuramaWhite** [comment]
still keeps giving error,  I went to install vhbl and he accepted good, but .. it's only with vitashell that does not catch, I do not know why, and now ??

**Comment by KuramaWhite** [comment]
![dsc_0121](https://user-images.githubusercontent.com/41026777/42482539-77e4e618-83be-11e8-89c8-4e44cd98439d.JPG)

**Comment by noahc3** [comment]
Did you make sure to install henkaku as well? I just retested and everything works fine.

**Comment by KuramaWhite** [comment]
Yes, I installed and the same error occurs !!!

**Comment by noahc3** [comment]
I'm honestly not sure, but it doesn't seem to be a problem with auto h-encore. It looks like it could happen with any application according to google, even official stuff. Maybe try asking on [/r/vitahacks](https://www.reddit.com/r/vitahacks/) in the questions thread, or on the [vita hacks discord](https://discord.gg/JXEKeg6).

Sorry I couldn't help!

**Comment by KuramaWhite** [comment]
I understand ... I'll wait for the most advanced unlocking, who knows? Thank you very much for your attention.

**Comment by barbabarros** [comment]
KuramaWhite,

Qual firmware você está usando? com henkaku, enso ou h-encore?
Você disse que formatou seu vita. Você formatou seu cartão também?
Você está usando sd2vita? o plugin está instalado corretamente?
Você está instalando o vitashell a partir de um arquivo VPK ou através de um backup do QCMA?
Todos os plugins estão atualizados na última versão?

**Comment by KuramaWhite** [comment]
olha a minha versão esta 3.68 eu instalei o vitashell pelo h-encore.
eu formatei tudo memoria interna e a memoria do cartão.
nao tenho sd2vita, para instalar os pluglin precisa entrar no vitashell né?(nao consigo entrar)
eu usei o programa qcma para transferir os dados para meu ps vita,e depois  iniciei o h-encore para instalar henkaku e vitashell, mas.. Nao consigo iniciar o vitashell

**Comment by barbabarros** [comment]
KuramaWhite,

Pra ser sincero ainda não instalei o h-encore. Irei fazer isso agora para tentar reproduzir esse erro.
Tenha um pouco de paciência e daqui a pouco eu volto aqui para lhe dar notícias.

(carregando o vita)

**Comment by KuramaWhite** [comment]
obrigado.. aguardo sua resposta.

**Comment by barbabarros** [comment]
KuramaWhite,

Eu segui esses passos e deu tudo certo.  Tem o passo a passo da instalação e configuração do vitashell também. Confere se fez tudo certo.

Lembre-se que toda vez que você ligar ou reiniciar o psvita, você precisa entrar no h-encore, escolher a opção Install Henkaku e depois selecione Exit. 

https://vita.hacks.guide/installing-h-encore

**Comment by barbabarros** [comment]
@noahc3 you can close it if you want because this is not an auto-h-encore error.

**Comment by noahc3** [comment]
Thanks for helping them out.

**Comment by KuramaWhite** [comment]
blz mano, vou fazer o processo, vamo ver se vai funcionar

**Comment by KuramaWhite** [comment]
desisto affff, acho que meu ps vita ta com erro de fabrica , mais muito obgg pela atenção
