### ISSUE TITLE
Error 2000-020D Occurred

### ISSUE THREAD

**Issue by mithrylaltaire** [noahc3/auto-h-encore#52]
Am on Windows 10 64 bit, using wifi connection to connect to internet.

Issue occurred when the tool attempted to import QCMA registry information

**Comment by noahc3** [comment]
I think you missed a number in the error code, it would never show 2000. Can you check again? It's necessary for me to figure out what's wrong.

**Comment by zequeiroz** [comment]
Boa noite estou com o erro 2001-020D, windows 10 64bits

**Comment by noahc3** [comment]
Could you guys try [this build](https://puu.sh/ATL2K/b594a3e4b3.zip) and see if it works?

**Comment by noahc3** [comment]
Could you guys try [the latest release](https://github.com/noahc3/auto-h-encore/releases/latest) and see if it works?

**Comment by mithrylaltaire** [comment]
![2001-020d](https://user-images.githubusercontent.com/41026973/42483927-8a0ae8d8-83be-11e8-9cd0-c438b41550e8.PNG)
This is what I got using 0.4.1

**Comment by noahc3** [comment]
Can you check if it is fixed in 0.4.2?

**Comment by mithrylaltaire** [comment]
I don't know, because I get this message when I try to open the .exe.  
![042](https://user-images.githubusercontent.com/41026973/42484175-a29fef50-83bf-11e8-9d24-7ef6c432f61a.PNG)

**Comment by noahc3** [comment]
Try extracting it to a different directory.

**Comment by mithrylaltaire** [comment]
That worked.  Now I'm getting a different issue.  Should I open a new ticket?

**Comment by noahc3** [comment]
Yes please

**Comment by mithrylaltaire** [comment]
This is what is happening now:
First this pops up:
![2018-07-09_2149](https://user-images.githubusercontent.com/41026973/42484644-f98b4d44-83c1-11e8-9eb3-be364691d33d.png)
Then my tray fills up with these:
![2018-07-09_2148](https://user-images.githubusercontent.com/41026973/42484650-06c1216e-83c2-11e8-8a1e-1f90706833b2.png)
Of course, through all this, the PS Vita fails to connect.
It is a 1000-series vita on 3.65 Henkaku Enso in airplane mode, and with the USB charging unchecked

**Comment by zequeiroz** [comment]
Resolvi mudando para uma pasta sem nenhum bloqueio de permissão.  Exemplo Documentos ou área de trabalho.
