### ISSUE TITLE
QCMA keeps opening and closing after attempting to connect to USB

### ISSUE THREAD

**Issue by mithrylaltaire** [noahc3/auto-h-encore#53]
This is what is happening now:
First this pops up:
![2018-07-09_2149](https://user-images.githubusercontent.com/41026973/42484716-551cf0a4-83c2-11e8-8f2f-74ce3ec21279.png)
Then my tray fills up with these:
![2018-07-09_2148](https://user-images.githubusercontent.com/41026973/42484724-60300bfc-83c2-11e8-97f7-b69716c3b4ed.png)
It does this over and over again. 

Of course, through all this, the PS Vita fails to connect.
It is a 1000-series vita on 3.65 Henkaku Enso in airplane mode, and with the USB charging unchecked.  I have created a PSN account

**Comment by noahc3** [comment]
This is intentional, as sometimes QCMA needs to be restarted for it to pick up the Vita. If you run your mouse over the icons, they should all disappear except one.

As for the Vita not connecting, did you make sure to try and copy content within Content Manager?

If that didn't work, can you:
 * Plug in your Vita
 * Shift-RightClick the Start button
 * Select Device Manager
 * Check if there is a category for libusbk devides
 * Make sure "PS Vita Type B" is listed under it.

**Comment by mithrylaltaire** [comment]
I did try and copy content within content manager.

In device manager, it shows:
![2018-07-09_2156](https://user-images.githubusercontent.com/41026973/42484875-0617a8ea-83c3-11e8-9cf9-2e7555cd50e2.png)

But nothing else.  I didn't get a little noise when I plugged in the vita either.  It is charging though, so something is working.  But other than that, its like the vita doesn't exist. 

Sorry, I know this is sort of beyond the scope of what you are trying to accomplish here.  This is a QCMA issue.  
*Sigh* well, I still got 3.65 enso at least. 

Thanks for all the help man! Your work is amazing, the QCMA issue notwithstanding!

**Comment by noahc3** [comment]
I assume you already had QCMA installed? The program won't try to overwrite the driver.

If you'd like to try install the driver this application uses, you can:
 * Download and extract [this QCMA redistribution](https://github.com/noahc3/auto-h-encore/blob/master/resources/qcma.zip)
 * Go into the driver folder
 * First run dpscat.exe
 * Then run dpinst64.exe (64 bit OS) or dpinst32.exe (32 bit OS) and accept all of the prompts.

Should show up like this after it is installed:
![image](https://puu.sh/ATO3v/a1ba116532.png)

**Comment by mithrylaltaire** [comment]
I followed the directions, and then restarted the PC, and it still just shows the one from before.

**Comment by noahc3** [comment]
Unfortunately I've got no idea.

I've been told that WiFi transfer DOES work on older firmwares as long as you follow the instructions [at the top of this page](https://vita.hacks.guide/installing-h-encore) and restart your Vita afterwards. Perhaps you could try that.

**Comment by calymos** [comment]
I've been having exactly the same issue, definitely gonna follow this thread.

**Comment by noahc3** [comment]
Any luck with Wifi?

**Comment by Hawaiian-Punch** [comment]
Same thing happens for me but I do not have any libusbK entries.  When trying to follow the steps to install them above it says install failed.
When I try to use WiFi the vita says I need a system update.  I am on 3.65 and my DNS is set as instructed along with disabling the auto download of system updates.

**Comment by Hawaiian-Punch** [comment]
I manually installed QCMA again and the USB option now also states a system update is needed.  auto h-encore still seems to launch multiple instances of QCMA though.

**Comment by calymos** [comment]
Hey, so I ended up just leaving it for a while, after backing up saves,
doing a system restore, and rebuilding the database- eventually the QCMA
worked and it installed. I dunno how helpful that is, but it eventually
"clicked" and now everything is running on my end.

If it's connecting through USB at all, I'd try just letting it keep
repeating that, cuz it worked for me.

Good luck!

**Comment by noahc3** [comment]
@Hawaiian-Punch Can you verify if running your mouse over the icons in task tray gets rid of them? It's true that the application restarts QCMA over and over to try and make it detect the device but it's supposed to kill the old QCMA process before launching a new one.

**Comment by Hawaiian-Punch** [comment]
Yes, it does get rid of them.  OK, thanks.  I must have misread the earlier posts.

**Comment by noahc3** [comment]
This will not be fixed as a better auto tool [finalhe by soarqin](https://github.com/soarqin/finalhe) has been released.
