### ISSUE TITLE
Error FFFF- 0106 

### ISSUE THREAD

**Issue by funbot28** [noahc3/auto-h-encore#59]
![image](https://user-images.githubusercontent.com/13896648/42577397-3bde8d10-84f2-11e8-85e5-68aa3c5b7322.png)

I keep getting this as an issue, I had tried to manually upload the h-encore folder previously with no success and now I try to do it automatically as it says it will delete any old files but it does not seem to work

**Comment by noahc3** [comment]
Unrelated to the h-encore file, it's failing to grab the content encryption key for some reason.

When you run the program, it should say the AID value in the log before that error occurs ("Getting CMA encryption key using AID xxxxxxxxxxxxxxxx")

Can you put that value into [this website](http://cma.henkaku.xyz/) and tell me whether it shows a string of 64 characters, or something else?

**Comment by funbot28** [comment]
Yup I get this: 

![image](https://user-images.githubusercontent.com/13896648/42604911-1285e232-8543-11e8-839d-03ac656fd0c5.png)

Any help?

**Comment by noahc3** [comment]
Could you try everything again with [this build?](https://github.com/noahc3/auto-h-encore/files/2186753/auto.h-encore_v0.4.3_DBG.BUILD.zip) It will report a more in depth error message, could you let me know what it says in full?

**Comment by funbot28** [comment]
I think it worked... where can I get homebrew applications?

**Comment by noahc3** [comment]
You can find homebrew [here](https://vitadb.rinnegatamante.it/#/)

For other questions you should ask on [/r/vitahacks](https://www.reddit.com/r/vitahacks/) in the weekly questions thread for better help.
