### ISSUE TITLE
Trimming down h-encore to 35MB

### ISSUE THREAD

**Issue by ghost** [noahc3/auto-h-encore#6]
[By using this method](https://www.reddit.com/r/vitahacks/comments/8vlp9h/hencore_from_261mb_to_35mb/), h-encore can be trimmed down to 35MB while still functioning enough to do the "trophy fix" trick.
Before sending the game to Vita, it _can_ be possible to delete those files and make it both smaller in size (a necessity for Sony cards) and faster to install. I haven't tested it since my Vita's hacked but _in theory_, it's a thing to look into.

**Comment by noahc3** [comment]
Added in commit 5ddec1d, verified working. Trims down to around 17MB.

**Comment by ghost** [comment]
Igi ari!      _Ace Attorney music rolls in_ 
I have a 9MB list! Every byte counts on a Sony memory card!

app\PCSG90096\resource\movie
app\PCSG90096\resource\image\bg
app\PCSG90096\resource\image\ev
app\PCSG90096\resource\image\icon
app\PCSG90096\resource\image\stitle
app\PCSG90096\resource\image\tachie
app\PCSG90096\resource\sound\bgm
app\PCSG90096\resource\sound\se
app\PCSG90096\resource\sound\sec
app\PCSG90096\resource\sound\voice
app\PCSG90096\resource\text\01
app\PCSG90096\sce_module\libsmart.suprx **(not sure about if this one can bring issues to be honest, since it's a plugin)**
app\PCSG90096\sce_sys\pic0.png
app\PCSG90096\sce_sys\icon0.png

**Comment by noahc3** [comment]
Commit bf56916 deletes everything you listed except the plugin. This is included on a prominent noob guide now, I don't want anything to break too much :P. Down to ~13MB . Thanks!

**Comment by ghost** [comment]
Princess of Sleeping released a h-encore.psvimg builder. Builds a h-encore with just 4MB size.
[Check it here.](http://mega.nz/#!MPpU0Y6D!1tAOyYi3iXj-yht_pZUif4LLJsSN1QcDuwzBy4yx8Xc)

**Comment by ghost** [comment]
Checked his build. Seems like he included the trimmed bitter smile. I doubt it's legal but it skips downloading bitter smile.

**Comment by noahc3** [comment]
That trims too much, trophy fix doesn't work, crashes the system if you try.

**Comment by ghost** [comment]
Trophy fix DOES work, Vita creates the save folder before game starts. Not much use (13 to 4 wouldn't make that much difference) but it's freaking hella cool.
