### ISSUE TITLE
Add Hungarian Translation

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [noahc3/auto-h-encore#61]
this is a edited language.cs with hungarian translate in this.
can u add to the program plz?
[https://www107.zippyshare.com/v/uIdOB5ea/file.html
](url)

**Comment by barbabarros** [comment]
@TheOneEyedGrimReaper you may use GitHub to add a new translation.

Please, use this link to edit: 

https://github.com/noahc3/auto-h-encore/edit/master/auto%20h-encore/Language.cs

 It will fork the project. Then you can send a pull request.

Thank you.

**Comment by noahc3** [comment]
I would recommend doing what barbabarros said. If I do it myself, you won't get correct attribution.

**Comment by TheOneEyedGrimReaper** [comment]
thanks.
i added and created a pull request on this.
