### ISSUE TITLE
Stuck at Install USB Driver

### ISSUE THREAD

**Issue by railcat** [noahc3/auto-h-encore#64]
stuck forever in installing USB driver
https://ibb.co/d1gego

Running on Intel Atom Netbook, OS Win 7  fresh install and framework 4.5,2 installed. any compatibility issue?

**Comment by noahc3** [comment]
The QCMA provided is 64 bit only, and it's likely that your atom is 32 bit. You can get around this by manually installing QCMA [here](https://codestation.github.io/qcma/) and then retrying the application.

**Comment by railcat** [comment]
yes, manual install QCMA and install all 3 driver. now h-encore appear on my vita.
Issue Solved. Thanks.
