### ISSUE TITLE
 vita 1000 , 3.68 , active psn account

### ISSUE THREAD

**Issue by v13ha** [noahc3/auto-h-encore#65]
Can't download h-encore through wi-fi , can't connect to pc with the cable
when i try to download h-encore via wi-fi it says "an error has occured C1-2758-2"
keep forward to hearing from you

**Comment by TheOneEyedGrimReaper** [comment]
try full factory reset: power off you vita,
press and hold the R button, PS button and the Power Button for 5 seconds.
and the 4th Restore the PS Vita System.
 sign in a psn account and activate the console.

if you come to teamviewer and skype i help you.
my skype id on my profile.

**Comment by v13ha** [comment]
I' ve already done all the suggested
I'll try to add ya on skype
