### ISSUE TITLE
System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by madster619** [noahc3/auto-h-encore#67]
So an error comes up in the visual studio, 

"System.ComponentModel.Win32Exception: 'The specified executable is not a valid application for this OS platform.'"

, and the application would freeze. The error pops up after installing USB driver. On the side note, should i use a memory card for the installation or is the sd2vita ok to use since im using sd2vita adapter? Thanks for the help

**Comment by noahc3** [comment]
Looks like you might be using an 32 bit OS. The QCMA this application installs is 64 bit only. You can still use this application, but you'll need to manually install QCMA yourself so it installs the 32 bit version. Afterwards, run the program again and it will use your install.

I don't know much about sd2vita, so I can't help you there. Sorry!
