### ISSUE TITLE
error - it was not possible to copy

### ISSUE THREAD

**Issue by guih2127** [noahc3/auto-h-encore#68]
it was not possible to copy the content

h - encore

you can only copy apps from your account

what can i do?

**Comment by noahc3** [comment]
Make sure your Vita has a PSN account linked and that the PSN account is signed in.

**Comment by guih2127** [comment]
I make it work by restarting my PC and disabling the security settings, thank you.

**Comment by noahc3** [comment]
@guih2127 Which security settings? For future reference.

**Comment by guih2127** [comment]
I disabled the Windows Firewall for complete and restarted my pc. I don't know exactly what was causing it, but the h-encore app was being created with 6kb instead of the original size.
