### ISSUE TITLE
Erro no desbloqueio do ps vita

### ISSUE THREAD

**Issue by Ramonziim** [noahc3/auto-h-encore#69]
Eu estou tentando fazer o desbloqueio do ps vita, pela primeira vez. Meu ps vita está na versão 3.68.
Fiz exatamente como mostra o tutorial, instalei a versão do net framework mais recente. Quando chega na parte que aparece uma pergunta sobre conectar o vita por wifi ou usb, tentei primeiramente por usb, pede pra desconectar o vita do pc caso esteja conectado, e clicar em prosseguir. Feito isso, aparece uma janela informando que está instalando o driver usb, e pede para aguardar, e a tela do H-Encore fica com a informação de que está pedindo informações ao usuário. Deixei nesse processo por mais de 10 horas e não saiu disso. Fechei o aplicativo e tentei por wifi, mas dá outro erro, com a seguinte mensagem: Ocorreu uma exceção sem tratamento no aplicativo. O executável especificado não é um aplicativo válido para esta plataforma de SO. Meu pc tem windows 10 32 bits, será que tem alguma coisa a ver? No caso esses programas são usados em arquitetura 64 bits?

![foto 1](https://user-images.githubusercontent.com/41556029/43052232-10b52a3e-8dfa-11e8-9568-ac7769ba2ca0.jpg)
![foto 2](https://user-images.githubusercontent.com/41556029/43052233-10e4cdde-8dfa-11e8-93d4-d9cb77b54af0.jpg)

**Comment by barbabarros** [comment]
@Ramonziim é por que o programa só funciona em arquitetura x64. O autor do programa já sinalizou que irá adicionar suporte aos usuários da plataforma 32 bits numa versão futura.

Enquanto isso, você pode tentar instalar uma máquina virtual com suporte x64 para efetuar o desbloqueio ou simplesmente utilizar outro computador. O ideal seria atualizar o seu SO para x64.

**Comment by Ramonziim** [comment]
@barbabarros Ah entendi, muito obrigado. Eu já estava querendo atualizar mesmo, só estava com preguiça AUHEUAHEUA
Irei fazer isso hoje mesmo, obrigado pela ajuda.

**Comment by noahc3** [comment]
You can manually install 32 bit QCMA for now to bypass this issue

@barbabarros maybe translate that JIC

**Comment by barbabarros** [comment]
@Ramonziim conforme autor do programa, você pode instalar o QCMA versão 32bits para consertar esse erro temporariamente.

Tenta lá e avise aqui.
