### ISSUE TITLE
Add 64x for "already file"

### ISSUE THREAD

**Issue by chronoss09** [noahc3/auto-h-encore#7]
![1e3a71adc37c24a9dec0e19fb5c85e93](https://user-images.githubusercontent.com/17669980/42203965-466c225c-7e98-11e8-9580-94b568abf942.png)

**Comment by noahc3** [comment]
Select "Ignore Mismatch File Hashes" for now, will fix in a later release.

**Comment by chronoss09** [comment]
ok !

**Comment by noahc3** [comment]
Commit 9949505 now allows x64 imports.
