### ISSUE TITLE
Moving H-encore files to the QCMA APP directory... 

### ISSUE THREAD

**Issue by Walo10** [noahc3/auto-h-encore#70]
Hello, I have this problem; Everything goes well until you get to the part  "Moving H-encore files to the QCMA APP directory... " That's all right.

![error](https://user-images.githubusercontent.com/41564421/43060169-61230bec-8e15-11e8-892c-18f015094685.png)

**Comment by noahc3** [comment]
Ill take a look into this and see if I can replicate it.

For now you can try manually moving it to the QCMA directory. Copy the folder ~/data/hencore/hencore/PCSG90096 to ~/PS Vita/APP/[AID]/ where your AID is 718c27b897ff4266

**Comment by noahc3** [comment]
This will not be fixed as a better auto tool [finalhe by soarqin](https://github.com/soarqin/finalhe) has been released.
