### ISSUE TITLE
error

### ISSUE THREAD

**Issue by milton1988** [noahc3/auto-h-encore#73]
**What happens**
[Description of the problem, what went wrong, etc]

**Error code (if applicable)**
[The error code shown by the application if one is shown (XXXX-XXXX)]

**Full error message (if applicable)**
[The full message of the error if one is shown]

**When does this happen**
[What were you doing when it happened, what were you trying to do, etc]

**System Information:**
 - OS: [ie. Windows 10 Pro x64]
 - CPU: [ie. AMD Ryzen 7 1700]
 - QCMA Preinstalled: [Yes/No]

**Additional information**
Add any other information about the problem here.

**Comment by milton1988** [comment]
Muchas gracias y entonces empezando para solucionar el. Problema a raiz qe
debo hacer ??

**Comment by noahc3** [comment]
This program is not being updated anymore.

Please use [finalhe by soarqin](https://github.com/soarqin/finalhe).
