### ISSUE TITLE
H encore stuck in white screen

### ISSUE THREAD

**Issue by EhryneLhae** [noahc3/auto-h-encore#77]
after running the Auto H Encore, there is a step on which after i copy the H encore, i need to run it. but every time i run, it is stuck on white screen, nothing happen. then when i close it, vita gets restarted. help

Please use [finalhe by soarqin](https://github.com/soarqin/finalhe).

**Comment by noahc3** [comment]
auto h-encore probably doesn't work anymore. Please use [finalhe by soarqin](https://github.com/soarqin/finalhe).
