### ISSUE TITLE
About QCMA

### ISSUE THREAD

**Issue by yexun1995** [noahc3/auto-h-encore#8]
A friend tell me this：
The Path of QCMA APP/Backup can be obtained from the regedit.
PC Name\HKEY_CURRENT_USER\Software\codestation\qcma
The string “appsPath”.
If you want to continue using QCMA, consider taking advantage of this.

**Comment by noahc3** [comment]
This is a lot better than the check I implemented. Will include, thanks!

**Comment by noahc3** [comment]
AID and QCMA directory are now gotten from registry in commit d7ef8ba
